apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-api-config
  namespace: dev
data:
  default.conf: |
    server {
      listen 80;

      # Kubernetes CoreDNS
      resolver 10.96.0.10 valid=10s;

      location /media/ {
        set $upstream "media.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /product/ {
        set $upstream "product.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /customer/ {
        set $upstream "customer.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /cart/ {
        set $upstream "cart.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /rating/ {
        set $upstream "rating.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /order/ {
        set $upstream "order.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /location/ {
        set $upstream "location.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /inventory/ {
        set $upstream "inventory.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /tax/ {
        set $upstream "tax.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /promotion/ {
        set $upstream "promotion.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /search/ {
        set $upstream "search.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /payment/ {
        set $upstream "payment.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /webhook/ {
        set $upstream "webhook.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /sampledata/ {
        set $upstream "sampledata.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
      location /recommendation/ {
        set $upstream "recommendation.dev.svc.cluster.local";
        proxy_pass http://$upstream;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config
          configMap:
            name: nginx-api-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
