backend:
  image:
    tag: "0e16117"
  replicaCount: 1
  ingress:
    enabled: true
    className: nginx
    host: api.yas.local.com
    path: /media
    pathType: ImplementationSpecific
  initContainers:
    - name: copy-sample-images
      image: danzgne/yas-sampledata:0e16117
      command: ["sh", "-c", "cd /tmp && unzip -q /app.jar 'BOOT-INF/classes/images/*' && cp -r /tmp/BOOT-INF/classes/images/sample /images/ && echo 'Images copied'"]
      volumeMounts:
        - name: media-images
          mountPath: /images
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
    - name: media-images
      emptyDir: {}
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
    - name: media-images
      mountPath: /images
