apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-payment
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/devops-hcmus/yas-cd
      targetRevision: main
      path: k8s/charts/payment
      helm:
        valueFiles:
          - values.yaml
          - $values/clusters/staging/payment/values.yaml
    - repoURL: https://github.com/devops-hcmus/gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
