apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-sampledata
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devops-hcmus/yas-cd
    targetRevision: main
    path: k8s/charts/sampledata
    helm:
      valueFiles:
        - values.yaml
        - https://raw.githubusercontent.com/devops-hcmus/gitops/main/clusters/staging/sampledata/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
