apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: staging-search
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/devops-hcmus/yas-cd
      targetRevision: v0.0.9
      path: k8s/charts/search
      helm:
        valueFiles:
          - values.yaml
          - $values/clusters/staging/search/values.yaml
    - repoURL: https://github.com/devops-hcmus/gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
